# Netlify Einstellungen

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"   # Service Worker immer frisch laden

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
